# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shopify_app_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: shopify_app_test
  host: localhost
  port: 5432


