:schedule:
  seed_products_and_variants_worker:
    every: '4h'
    class: SeedProductsAndVariantsWorker
  query_google_api_worker:
    every: '4h' ## ideally this starts on the hour
    class: QueryGoogleApiWorker
  product_view_threshold_worker:
    every: '4.5h' ## TODO ideally this start at :30m past the hour
    class: ProductViewThresholdWorker
