:schedule:
  seed_products_and_variants_worker:
    every: '2h'
    class: SeedProductsAndVariantsWorker
  query_google_api_worker:
    every: '1h' ## ideally this starts on the hour
    class: QueryGoogleApiWorker
  product_view_threshold_worker:
    every: '90m' ## TODO ideally this start at :30m past the hour
    class: ProductViewThresholdWorker
